name: Publish

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - ".github/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - run: apt-get install imagemagick
      - run: apt-get install graphicsmagick
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          local-dir: "build/"
          log-level: minimal
